import type { MSAData } from "./types";
export const exampleMsa: MSAData = [
  {
    header:
      "sp|Q5YGP8|PLET1_ARATH AP2-like ethylene-responsive transcription factor PLT1 OS=Arabidopsis thaliana OX=3702 GN=PLT1 PE=2 SV=1",
    sequence:
      "M------------------------NSNNWLGFPLSPNN------------------------------SSLPPH----------------EYNLGLVSDHMDNPFQTQ---------EWNM----INPHGGG----GDEGGEVPKVADFLGVSKPDENQSNH--------------------------LVAYN---D------------------------SDYY---FHTN----SLMPSVQSNDVVVAACDSNTPNNSSYHELQES----AHNLQSLT----------------LSMGTT----------------------------AGNNVVDKASPSETT-----GDNA------SGGALAVVETATPRRALDTFGQRTSIYRGVTRHRWTGRYEAHLWDNSCRREGQSRKGRQVYLGGYDKEDKAARSYDLAALKYWGPSTTTNFPITNYEKEVEEMKHMTRQEFVAAIRRKSSGFSRGASMYRGVTRHHQHGRWQARIGRVAGNKDLYLGTFSTEEEAAEAYDIAAIKFRGLNAVTNFEINRY-----DVKAILESSTLPIGGGAAKRLKEA-----QALESSRKREAEMIALGSS-F-------QYGGGSSTGSGSTSSRLQLQPYPLSIQQPLE-----------PFLSLQ-NNDISHYNNNNAHDSSSFNHHSY----IQTQLHLH-QQTNNYLQ----QQSSQNS-QQLYNAYLHSNPALLHGLVSTSIVDNNNNNGGSSGS----YNTAAFLGNHGIGIGSSSTVGST--EEFPTVKTDYDMPSSDGTGGYSGWTS-ESVQ---------------------------------GSNPGGVFTMWNE---",
  },
  {
    header:
      "sp|Q5YGP7|PLET2_ARATH AP2-like ethylene-responsive transcription factor PLT2 OS=Arabidopsis thaliana OX=3702 GN=PLT2 PE=2 SV=1",
    sequence:
      "M------------------------NSNNWLAFPLSPTH------------------------------SSLPPHI---------HSSQNSHFNLGLVNDNIDNPFQNQ---------GWNM----INPHGGG----G-EGGEVPKVADFLGVSKSGDHHTDH-------------------------NLVPYN---DI---------HQTN---------ASDYY---FQTN----SLLPT-------VVTCASNAPNN---YELQES----AHNLQSLT----------------LSMGST-------------------------GAAAAEVATVKASPAETS-----ADNSSSTTNTSGGAIV---EATPRRTLETFGQRTSIYRGVTRHRWTGRYEAHLWDNSCRREGQSRKGRQVYLGGYDKEEKAARAYDLAALKYWGPSTTTNFPITNYEKEVEEMKNMTRQEFVASIRRKSSGFSRGASMYRGVTRHHQHGRWQARIGRVAGNKDLYLGTFSTEEEAAEAYDIAAIKFRGLNAVTNFEINRY-----DVKAILESNTLPIGGGAAKRLKEA-----QALESSRKRE-EMIALGSN-FH------QYGAASGSSSVASSSRLQLQPYPLSIQQPFEH-----LHHHQPLLTLQNNNDISQYH-----DS-----FSY----IQTQLHLHQQQTNNYL------QSSSHT-SQLYNAYLQSNPGLLHGFVS----DNN--------------NTSGFLGNNGIGIGSSSTVGSSAEEEFPAVKVDYDMPPSGGATGYGGWNSGESAQ---------------------------------GSNPGGVFTMWNE---",
  },
  {
    header:
      "sp|Q6PQQ3|AIL5_ARATH AP2-like ethylene-responsive transcription factor AIL5 OS=Arabidopsis thaliana OX=3702 GN=AIL5 PE=2 SV=2",
    sequence:
      "MKNNNNKSSSSSSYDSSLSPSSSSSSHQNWLSFSLSNNNNNF--NSSSNPNLTS---ST---------SDHHHPH----------------PSHLSLFQAFSTSPVERQDGSPGVSPSDATAVLS-VYPGG-------------PKLENFLGGGASTTTTRPM---------------------------------------------QQVQ--SLGGVVFSSDLQ-----------PPLHPPSAAEIYDSELKSIAASF---LGNYSG----GH--------------------------------------------------------SSEVSSVHKQQPNPL----------------AVSEA---SPTPKKNVESFGQRTSIYRGVTRHRWTGRYEAHLWDNSCRREGQSRKGRQVYLGGYDKEDKAARAYDLAALKYWGPTTTTNFPISNYESELEEMKHMTRQEFVASLRRKSSGFSRGASMYRGVTRHHQHGRWQARIGRVAGNKDLYLGTFSTQEEAAEAYDIAAIKFRGLNAVTNFDISRY-----DVKSIASCNLP-VGGLMPKPSPAT-----AAADKTV------------------------DLSPSDSPSLTTPS--LTFNVA-----------------TPVNDHGGTFYHTGI---PIKPDPADHYWSNIFGFQANPKAEMRPLANF----GSDLHNPSPGYAIMPVMQEGENNFGGSFVGSDGYNNHSAASNPVSAIPLSSTTTMSNGNEGY--------GGN---------INW--------INNNISSSYQTAKSNLSV------------------------------LHTPVFGLE-----",
  },
  {
    header:
      "sp|Q6PQQ4|BBM_ARATH AP2-like ethylene-responsive transcription factor BBM OS=Arabidopsis thaliana OX=3702 GN=BBM PE=2 SV=2",
    sequence:
      "M-----------------------NSMNNWLGFSLSPHDQNH--HRTDVDSSTT---RTAVDVAGGYCFDLAAPS----DESSAVQTSFLSPFGVTLEAFTRDNNSHSR---------DWDI-------NGGACNNINNNEQNGPKLENFLGRT--TTIYNTN-ETVV-----------------------------DGN--GDCGGGDGGGGGSLGLSMIKTWLS----------------------------NHSVAN---ANHQDN----GNGARGLS----------------LSMNSS-------------------------TSDSNNYNNNDDVVQEKT----------------IVDVV---ETTPKKTIESFGQRTSIYRGVTRHRWTGRYEAHLWDNSCKREGQTRKGRQVYLGGYDKEEKAARAYDLAALKYWGTTTTTNFPLSEYEKEVEEMKHMTRQEYVASLRRKSSGFSRGASIYRGVTRHHQHGRWQARIGRVAGNKDLYLGTFGTQEEAAEAYDIAAIKFRGLSAVTNFDMNRY-----NVKAILESPSLPI-GSSAKRLKDVNNPVPAMMISNNVSE------------------SANNVSGWQNTAFQHHQGMDL---------------------SLLQQQQERYVGYYN--------------------------------------GGNLSTEST-RVCFKQEEEQQHFLRNSPSHMTNVDHHSSTSDDSVTVC--GNVVSYGGYQGFAI----PVGTS---------VNYD-PFTAAEIAYNARNHYYYAQHQQQQQIQQSPGGDFPVAISNNHSSNMYFHGEGGGEGAPTFSVWNDT--",
  },
  {
    header:
      "sp|Q1PFE1|AIL1_ARATH AP2-like ethylene-responsive transcription factor AIL1 OS=Arabidopsis thaliana OX=3702 GN=AIL1 PE=2 SV=1",
    sequence:
      "M--------------------------KKWLGFSLTPPLRI---CNSEEEELRH-------------------------D--------------------------------------GSDVWRYDINFDHH------HHDEDVPKVEDLLSNSHQTEYPINHNQTNVNCTTVVNRLNPPGYLLHDQTVVTPHYPNLDPNLSNDYGGFERVG----SVSVFKSWLEQ---------GTPAFPLSSHYVTEEAGTSNNISH---FSNEET----GYNTNGSM----------------LSLALS----------------------HGACSDLINESNVSARVEEPV-----KVDEKRKRLVVKPQVK---ESVPRKSVDSYGQRTSQYRGVTRHRWTGRYEAHLWDNSCKKEGQTRRGRQVYLGGYDEEEKAARAYDLAALKYWGPTTHLNFPLSNYEKEIEELNNMNRQEFVAMLRRNSSGFSRGASVYRGVTRHHQHGRWQARIGRVAGNKDLYLGTFSTQEEAAEAYDIAAIKFRGLNAVTNFDINRY-----DVKRICSSSTI-VDSDQAKHSPTSS-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GAG---------------------------------------------------------------------------------H",
  },
  {
    header:
      "sp|Q38914|ANT_ARATH AP2-like ethylene-responsive transcription factor ANT OS=Arabidopsis thaliana OX=3702 GN=ANT PE=1 SV=2",
    sequence:
      "MK---------SFCDND---DNNHSNTTNLLGFSLSSNMMKMGGRGGREAIYSSS-TSSAATS-----SSSVPPQLVVGDNTSNFGVCYGSNPNGGIYSHMSVMPLRSD---------GSLCLMEALNRSSHS----NHHQDSSPKVEDFFGTHHNNTSHKEA---------------------MD-LSL-------D--------------------SLFYNTTH-----------EPNTTTNFQEFFSFPQTRNHEEE---TRNYGNDPSLTH---GGS-FNVGVYGEFQ---QSLSLSMSPGSQSSCITGSHHHQQNQNQNHQSQNHQQISEALVETSVGFETTTMAAAKKKRGQEDVVVVGQK---QIVHRKSIDTFGQRTSQYRGVTRHRWTGRYEAHLWDNSFKKEGHSRKGRQVYLGGYDMEEKAARAYDLAALKYWGPSTHTNFSAENYQKEIEDMKNMTRQEYVAHLRRKSSGFSRGASIYRGVTRHHQHGRWQARIGRVAGNKDLYLGTFGTQEEAAEAYDVAAIKFRGTNAVTNFDITRY-----DVDRIMSSNTL-LSGELARRNNNS-----IVVRNTE----DQTALNAV-------------VEGGSNKEVSTPERLLSFPAI-----------------FALPQVNQKMFGSNM--------------------------------------GGNMSPWTS---------------------------NPNAELKTVALTL--------------------------------------P------------------------------------------------------QMPVFAAWADS--",
  },
  {
    header:
      "sp|Q52QU2-2|AIL6_ARATH Isoform 2 of AP2-like ethylene-responsive transcription factor AIL6 OS=Arabidopsis thaliana OX=3702 GN=AIL6",
    sequence:
      "MM----------------------APMTNWLTFSLSPMEML---RSSDQSQFVSYDASS---------AASSSPYLL--D---NFYGWSNQKPQEF-------FKEEAQL-AAAASMADSTILTTFVDPQSH------HSQNHIPKLEDFLGDSSSIVRYSDNSQTDT----------------QD-SSLTQIY---DPR--------HH-----HNQTGFYSDHH--DFKTMAGFQSAFSTNSGSEVDD------SASI---GRTHLAGDYLGHVVESSG-PELGFHGGST---GALSLGVNVNNN------TNHRNDNDNHYRGNNNGERINNNNNND---------NEKTDSEKEKAVVAVETS---DCSNKKIADTFGQRTSIYRGVTRHRWTGRYEAHLWDNSCRREGQARKGRQVYLGGYDKEDKAARAYDLAALKYWNATATTNFPITNYSKEVEEMKHMTKQEFIASLRRKSSGFSRGASIYRGVTRHHQQGRWQARIGRVAGNKDLYLGTFATEEEAAEAYDIAAIKFRGINAVTNFEMNRY-----DVEAIMKSALP-IGGAAKRLK--------LSLEAAASSE-QKPILGHHQLHHFQQQQQQQQLQLQSSPNHSS----INFALC-----------------PNSAVQSQQIIPCGI---PFEAAALYHHHQ-----QQQQHQQQQQQQNFFQHFPANAASDST-----------------------GSNNNSNVQGTMGLMA---------------------------------------P------------------------------------------------------NPAEFFLWPNQSY",
  },
  {
    header:
      "sp|Q52QU2|AIL6_ARATH AP2-like ethylene-responsive transcription factor AIL6 OS=Arabidopsis thaliana OX=3702 GN=AIL6 PE=2 SV=1",
    sequence:
      "MM----------------------APMTNWLTFSLSPMEML---RSSDQSQFVSYDASS---------AASSSPYLL--D---NFYGWSNQKPQEF-------FKEEAQL-AAAASMADSTILTTFVDPQSH------HSQNHIPKLEDFLGDSSSIVRYSDNSQTDT----------------QD-SSLTQIY---DPR--------HH-----HNQTGFYSDHH--DFKTMAGFQSAFSTNSGSEVDD------SASI---GRTHLAGDYLGHVVESSG-PELGFHGGST---GALSLGVNVNNN------TNHRNDNDNHYRGNNNGERINNNNNND---------NEKTDSEKEKAVVAVETS---DCSNKKIADTFGQRTSIYRGVTRHRWTGRYEAHLWDNSCRREGQARKGRQ---GGYDKEDKAARAYDLAALKYWNATATTNFPITNYSKEVEEMKHMTKQEFIASLRRKSSGFSRGASIYRGVTRHHQQGRWQARIGRVAGNKDLYLGTFATEEEAAEAYDIAAIKFRGINAVTNFEMNRY-----DVEAIMKSALP-IGGAAKRLK--------LSLEAAASSE-QKPILGHHQLHHFQQQQQQQQLQLQSSPNHSS----INFALC-----------------PNSAVQSQQIIPCGI---PFEAAALYHHHQ-----QQQQHQQQQQQQNFFQHFPANAASDST-----------------------GSNNNSNVQGTMGLMA---------------------------------------P------------------------------------------------------NPAEFFLWPNQSY",
  },
  {
    header:
      "sp|Q6J9N8|AIL7_ARATH AP2-like ethylene-responsive transcription factor AIL7 OS=Arabidopsis thaliana OX=3702 GN=AIL7 PE=2 SV=2",
    sequence:
      "MA----------------------PPMTNCLTFSLSPMEML---KSTDQSHFSS---SY---------DDSSTPYLI--D---NFYA----------------FKEEAEIEAAAASMADSTTLSTFFD----------HSQTQIPKLEDFLGDS--FVRYSDN-QTET----------------QDSSSLTPFY---DPR--------HRTV--AEGVTGFFSDHHQPDFKTI---------NSGPEIFDD---STTSNI---GGTHLS----SHVVESSTTAKLGFNGDCTTTGGVLSLGVN---------------NTSDQPLSCNNGERGGNSN-------------------KKKTVSKKETS---DDSKKKIVETLGQRTSIYRGVTRHRWTGRYEAHLWDNSCRREGQARKGRQVYLGGYDKEDRAARAYDLAALKYWGSTATTNFPVSSYSKELEEMNHMTKQEFIASLRRKSSGFSRGASIYRGVTRHHQQGRWQARIGRVAGNKDLYLGTFATEEEAAEAYDIAAIKFRGINAVTNFEMNRY-----DIEAVMNSSLP-VGGAAAKRHKLK-----LALESPSSSS-S------------DHNLQQQQLLPSSSPSDQN---------------------------PNS-------IPCGI---PFEPSVLYYH------------------QNFFQHYP--LVSDST------------------------------IQAPM--------------------------------------------------------------------------------------------------NQAEFFLWPNQSY",
  },
  {
    header:
      "sp|Q94AN4|AP2L1_ARATH AP2-like ethylene-responsive transcription factor At1g16060 OS=Arabidopsis thaliana OX=3702 GN=At1g16060 PE=2 SV=1",
    sequence:
      "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------MFIAVE----------------------VSPVMEDITRQSKKTSVENET-----GDDQSATS--VVLKAK---RKRRSQPRDAPPQRSSVHRGVTRHRWTGRYEAHLWDKNSWNETQTKKGRQVYLGAYDEEDAAARAYDLAALKYWGRDTILNFPLCNYEEDIKEMESQSKEEYIGSLRRKSSGFSRGVSKYRGVAKHHHNGRWEARIGRVFGNKYLYLGTYATQEEAAIAYDIAAIEYRGLNAVTNFDISRYLKLPVPENPIDTANNL-LESPHSDLSPF--------IKPNHESD------------------LSQSQSSSEDNDDRKTKLLKSSPLVAEEVIGPSTPPEIAPPRRSFPEDIQTYFGCQN--------------------------------------SGKLTAEED-DVIF--------------------------------------------------------------------------------------------------------------------------GDLDSFLTPDFYSELND-C",
  },
];
